namespace EmbeddedBuildProperty;

using System.Text;

using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis;

public sealed partial class Generator
{
    private const string AttributeSource = @"// <auto-generated />
using System;

namespace EmbeddedBuildProperty
{
    [System.Diagnostics.Conditional(""COMPILE_TIME_ONLY"")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
    public sealed class BuildProperty : Attribute
    {
        public BuildProperty()
        {
        }

        public BuildProperty(string s)
        {
        }
    }
}
";

    private static void AddAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("BuildPropertyAttributes", SourceText.From(AttributeSource, Encoding.UTF8));
    }
}
